# Generated by Django 5.1.1 on 2024-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_done", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[("H", "Hight"), ("M", "Medium"), ("L", "Low")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
